version: '3.8'

services:
  whatsapp-mcp:
    build: .
    ports:
      - "8081:8081"  # MCP server port with SSE
      - "8082:8082"  # Gradio UI port
    volumes:
      - ./store:/app/whatsapp-bridge/store  # Persistent storage for WhatsApp data
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      -  n8n_n8n_traefik_network
networks:
  n8n_n8n_traefik_network:
    external: true